In [6]:
install.packages("tictoc")

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [1]:
setwd("/mnt/gsdata/projects/panops/panops-data-registry/data/flux")

In [2]:
library(dplyr)
library(data.table)
library(purrr)
library(readr)
library(stringr)
library(tools)  # for file_path_sans_ext
library(tictoc)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last



Attaching package: ‘purrr’


The following object is masked from ‘package:data.table’:

    transpose



Attaching package: ‘tictoc’


The following object is masked from ‘package:data.table’:

    shift

In [ ]:

# --- 1. Your rename_map -------------------------------------------------

rename_map <- c(
  "CO2_F_MDS"             = "CO2",
  "CO2_F_MDS_QC"          = "CO2_QC",
  "GPP_DT_VUT_REF"        = "GPP_DT",
  "GPP_NT_VUT_REF"        = "GPP_NT",
  "G_F_MDS"               = "G",
  "G_F_MDS_QC"            = "G_QC",
  "H_CORR"                = "H_CORR",
  "H_F_MDS"               = "H",
  "H_F_MDS_QC"            = "H_QC",
  "H_RANDUNC"             = "H_RANDUNC",
  "H_RANDUNC_N"           = "H_RANDUNC_N",
  "LE_CORR"               = "LE_CORR",
  "LE_F_MDS"              = "LE",
  "LE_F_MDS_QC"           = "LE_QC",
  "LE_RANDUNC"            = "LE_RANDUNC",
  "LE_RANDUNC_N"          = "LE_RANDUNC_N",
  "LW_IN_F"               = "LW_IN",
  "LW_OUT"                = "LW_OUT",
  "NEE_VUT_REF"           = "NEE",
  "NEE_VUT_REF_QC"        = "NEE_QC",
  "NEE_VUT_REF_RANDUNC"   = "NEE_RANDUNC",
  "NEE_VUT_REF_RANDUNC_N" = "NEE_RANDUNC_N",
  "NETRAD"                = "NETRAD",
  "NIGHT"                 = "NIGHT",
  "P_F"                   = "P",
  "PA"                    = "PA",
  "PPFD_DIF"              = "PPFD_DIF",
  "PPFD_IN"               = "PPFD_IN",
  "PPFD_OUT"              = "PPFD_OUT",
  "RECO_DT_VUT_REF"       = "RECO_DT",
  "RECO_NT_VUT_REF"       = "RECO_NT",
  "SWC_F_MDS_1"           = "SWC_1",
  "SWC_F_MDS_1_QC"        = "SWC_1_QC",
  "SWC_F_MDS_2"           = "SWC_2",
  "SWC_F_MDS_2_QC"        = "SWC_2_QC",
  "SW_IN_F"               = "SW_IN",
  "SW_IN_F_QC"            = "SW_IN_QC",
  "SW_OUT"                = "SW_OUT",
  "SW_IN_POT"             = "SW_IN_POT",
  "TA_F"                  = "TA",
  "TA_F_QC"               = "TA_QC",
  "TS_F_MDS_1"            = "TS_1",
  "TS_F_MDS_2"            = "TS_2",
  "TS_F_MDS_1_QC"         = "TS_1_QC",
  "TS_F_MDS_2_QC"         = "TS_2_QC",
  "USTAR"                 = "USTAR",
  "VPD_F"                 = "VPD",
  "VPD_F_QC"              = "VPD_QC"
)

In [3]:
# --- 2. Helper: read one file, clean colnames, add SITE_ID --------------

read_and_clean_site <- function(path) {
  site_id <- file_path_sans_ext(basename(path))
  
  df <- read_csv(path, show_col_types = FALSE)
  
  # Only rename columns that actually exist in this file
  cols_to_rename <- intersect(names(rename_map), names(df))
  
  # dplyr::rename() expects new_name = old_name
  # Our rename_map is old_name = new_name, so invert it here
  rename_vec <- setNames(cols_to_rename, rename_map[cols_to_rename])
  
  df <- df %>%
    rename(!!!rename_vec) %>%
    mutate(SITE_ID = site_id)
  
  df
}

In [ ]:
library(tictoc)

In [4]:
# --- 3. Read all site files into a named list ---------------------------

csv_files <- list.files(
  path = "merged_sites_subset",
  pattern = "\\.csv$",
  full.names = TRUE
)
# Now you have: site_list[["DE-Hai"]] etc.

In [ ]:
output_dir <- "merged_sites_subset_renamed"
dir.create(output_dir, showWarnings = FALSE)
tic("Reading all sites")
walk(csv_files, function(path) {
  site_id <- file_path_sans_ext(basename(path)) |>
  sub("_merged$", "", .)
  site_df <- read_and_clean_site(path)
  out_path <- file.path(output_dir, paste0(site_id, ".csv"))
  write_csv(site_df, out_path)
})
toc()

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”

Reading all sites: 7984.693 sec elapsed

In [10]:
#lets read one of the files
library(data.table)
flux_data <- fread("merged_sites_subset_renamed/DE-Hai_merged.csv")
str(flux_data)

Attaching package: ‘data.table’


The following object is masked from ‘package:tictoc’:

    shift


The following object is masked from ‘package:purrr’:

    transpose


The following objects are masked from ‘package:dplyr’:

    between, first, last

Classes ‘data.table’ and 'data.frame':	72596 obs. of  67 variables:
 $ TIMESTAMP_START:integer64 200001010000 200001010030 200001010100 200001010130 200001010200 200001010230 200001010300 200001010330 ...
 $ TIMESTAMP_END  :integer64 200001010030 200001010100 200001010130 200001010200 200001010230 200001010300 200001010330 200001010400 ...
 $ TA             : num  -0.58 -0.64 -0.6 -0.53 -0.5 -0.43 -0.37 -0.35 -0.32 -0.26 ...
 $ TA_QC          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ VPD            : num  0.248 0.153 0.092 0.104 0.106 0.107 0.111 0.109 0.109 0.14 ...
 $ VPD_QC         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ P              : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_F_QC         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ TS_1           : num  1.18 1.16 1.16 1.17 1.18 ...
 $ TS_2           : num  1.45 1.44 1.44 1.45 1.45 ...
 $ TS_1_QC        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ TS_2_QC        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ WS_F           : num  2.17 2.56 3.15 3.13 2.89 3.65 4.17 3.77 3.14 2.87 ...
 $ WS_F_QC        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ SWC_1          : num  -9999 -9999 -9999 -9999 -9999 ...
 $ SWC_2          : num  -9999 -9999 -9999 -9999 -9999 ...
 $ SWC_1_QC       : int  -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 ...
 $ SWC_2_QC       : int  -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 ...
 $ H_CORR         : num  -6.79 -8.06 -8.14 -10.64 -9.89 ...
 $ H_RANDUNC      : num  24.1 16.9 23.6 22.3 23.2 ...
 $ H_RANDUNC_N    : int  6 6 6 7 7 76 6 8 8 9 ...
 $ NEE_RANDUNC_N  : int  90 91 90 90 90 77 90 90 90 87 ...
 $ LE             : num  -3.64 -3.41 -2.06 -3.96 -2.39 ...
 $ LE_QC          : int  1 1 0 1 0 1 0 1 1 1 ...
 $ LE_CORR        : num  -2.81 -2.64 -1.6 -3.09 -1.86 ...
 $ LE_RANDUNC     : num  5.37 5.37 5.38 5.37 5.38 ...
 $ LE_RANDUNC_N   : int  216 216 220 217 221 220 223 221 222 223 ...
 $ H              : num  -8.8 -10.4 -10.5 -13.7 -12.7 ...
 $ H_QC           : int  0 0 0 0 0 1 0 0 0 0 ...
 $ CO2            : num  380 381 381 382 383 ...
 $ CO2_QC         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ NEE            : num  1.13 1.09 1.13 1.21 1.21 ...
 $ NEE_QC         : int  1 1 1 1 1 0 0 1 1 0 ...
 $ NEE_VUT_50     : num  1.15 1.09 1.15 1.25 1.25 ...
 $ NEE_VUT_50_QC  : int  1 1 1 1 1 0 0 1 1 0 ...
 $ NEE_RANDUNC    : num  0.787 0.79 0.787 0.787 0.787 ...
 $ GPP_NT         : num  -0.0859 -0.045 -0.0874 -0.1618 -0.1596 ...
 $ GPP_DT         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ GPP_NT_VUT_50  : num  -0.128 -0.095 -0.129 -0.237 -0.235 ...
 $ GPP_DT_VUT_50  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ RECO_NT        : num  1.04 1.04 1.04 1.05 1.05 ...
 $ RECO_DT        : num  1.16 1.16 1.16 1.16 1.16 ...
 $ RECO_NT_VUT_50 : num  1.04 1.04 1.04 1.04 1.05 ...
 $ RECO_DT_VUT_50 : num  1.16 1.16 1.16 1.16 1.16 ...
 $ SW_IN          : num  0 0 0 0 0 0 0 0 0 0 ...
 $ SW_IN_QC       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ PPFD_IN        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ PPFD_DIF       : num  -9999 -9999 -9999 -9999 -9999 ...
 $ PPFD_OUT       : int  -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 ...
 $ TA_F_MDS       : num  -0.58 -0.64 -0.6 -0.53 -0.5 -0.43 -0.37 -0.35 -0.32 -0.26 ...
 $ TA_F_MDS_QC    : int  0 0 0 0 0 0 0 0 0 0 ...
 $ VPD_F_MDS      : num  0.248 0.153 0.092 0.104 0.106 0.107 0.111 0.109 0.109 0.14 ...
 $ SW_IN_F_MDS    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ SW_IN_F_MDS_QC : int  0 0 0 0 0 0 0 0 0 0 ...
 $ SW_IN_POT      : num  0 0 0 0 0 0 0 0 0 0 ...
 $ LW_IN          : num  308 309 308 307 309 ...
 $ LW_OUT         : num  313 313 313 313 313 ...
 $ SW_OUT         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ NETRAD         : num  -5.06 -3.91 -4.6 -6.35 -4.38 ...
 $ USTAR          : num  -9999 0.622 -9999 -9999 0.86 ...
 $ WS             : num  2.17 2.56 3.15 3.13 2.89 3.65 4.17 3.77 3.14 2.87 ...
 $ G              : num  -4.87 -4.87 -4.86 -4.86 -4.86 ...
 $ G_QC           : int  0 0 0 0 0 0 0 0 0 0 ...
 $ RH             : num  95.8 97.4 98.4 98.2 98.2 ...
 $ NIGHT          : num  1 1 1 1 1 1 1 1 1 1 ...
 $ PA             : num  96.6 96.6 96.6 96.6 96.6 ...
 $ SITE_ID        : chr  "DE-Hai_merged" "DE-Hai_merged" "DE-Hai_merged" "DE-Hai_merged" ...
 - attr(*, ".internal.selfref")=<externalptr>

In [11]:
colnames(flux_data)

 [1] "TIMESTAMP_START" "TIMESTAMP_END"   "TA"              "TA_QC"
 [5] "VPD"             "VPD_QC"          "P"               "P_F_QC"
 [9] "TS_1"            "TS_2"            "TS_1_QC"         "TS_2_QC"
[13] "WS_F"            "WS_F_QC"         "SWC_1"           "SWC_2"
[17] "SWC_1_QC"        "SWC_2_QC"        "H_CORR"          "H_RANDUNC"
[21] "H_RANDUNC_N"     "NEE_RANDUNC_N"   "LE"              "LE_QC"
[25] "LE_CORR"         "LE_RANDUNC"      "LE_RANDUNC_N"    "H"
[29] "H_QC"            "CO2"             "CO2_QC"          "NEE"
[33] "NEE_QC"          "NEE_VUT_50"      "NEE_VUT_50_QC"   "NEE_RANDUNC"
[37] "GPP_NT"          "GPP_DT"          "GPP_NT_VUT_50"   "GPP_DT_VUT_50"
[41] "RECO_NT"         "RECO_DT"         "RECO_NT_VUT_50"  "RECO_DT_VUT_50"
[45] "SW_IN"           "SW_IN_QC"        "PPFD_IN"         "PPFD_DIF"
[49] "PPFD_OUT"        "TA_F_MDS"        "TA_F_MDS_QC"     "VPD_F_MDS"
[53] "SW_IN_F_MDS"     "SW_IN_F_MDS_QC"  "SW_IN_POT"       "LW_IN"
[57] "LW_OUT"          "SW_OUT"          "NETRAD"          "USTAR"
[61] "WS"              "G"               "G_QC"            "RH"
[65] "NIGHT"           "PA"              "SITE_ID"

In [7]:
all_site_locations <- fread("all_tower_location_cleaned.csv")

In [8]:
View(all_site_locations)

    SITE_ID SITE_NAME                                             FLUXNET2015
1   AR-SLu  San Luis                                              CC-BY-4.0
2   AR-Vir  Virasoro                                              CC-BY-4.0
3   AT-Neu  Neustift                                              CC-BY-4.0
4   AU-ASM  Alice Springs                                         CC-BY-4.0
5   AU-Ade  Adelaide River                                        CC-BY-4.0
6   AU-Cpr  Calperum                                              CC-BY-4.0
7   AU-Cum  Cumberland Plain                                      CC-BY-4.0
8   AU-DaP  Daly River Pasture                                    CC-BY-4.0
9   AU-DaS  Daly River Savanna                                    CC-BY-4.0
10  AU-Dry  Dry River                                             CC-BY-4.0
11  AU-Emr  Emerald                                               CC-BY-4.0
12  AU-Fog  Fogg Dam                                              CC-BY-4.0
13  AU-GWW  Great Western Woodlands, Western Australia, Australia CC-BY-4.0
14  AU-Gin  Gingin                                                CC-BY-4.0
15  AU-How  Howard Springs                                        CC-BY-4.0
16  AU-Lox  Loxton                                                CC-BY-4.0
17  AU-RDF  Red Dirt Melon Farm, Northern Territory               CC-BY-4.0
18  AU-Rig  Riggs Creek                                           CC-BY-4.0
19  AU-Rob  Robson Creek, Queensland, Australia                   CC-BY-4.0
20  AU-Stp  Sturt Plains                                          CC-BY-4.0
21  AU-TTE  Ti Tree East                                          CC-BY-4.0
22  AU-Tum  Tumbarumba                                            CC-BY-4.0
23  AU-Wac  Wallaby Creek                                         CC-BY-4.0
24  AU-Whr  Whroo                                                 CC-BY-4.0
25  AU-Wom  Wombat                                                CC-BY-4.0
26  AU-Ync  Jaxa                                                  CC-BY-4.0
27  BE-Bra  Brasschaat                                            CC-BY-4.0
28  BE-Lon  Lonzee                                                CC-BY-4.0
29  BE-Vie  Vielsalm                                              CC-BY-4.0
30  BR-Npw  Northern Pantanal Wetland                             NA
⋮   ⋮       ⋮                                                     ⋮
238 US-StJ  St Jones Reserve                                      NA
239 US-Sta  Saratoga                                              CC-BY-4.0
240 US-Syv  Sylvania Wilderness Area                              CC-BY-4.0
241 US-Ton  Tonzi Ranch                                           CC-BY-4.0
242 US-Tw1  Twitchell Wetland West Pond                           CC-BY-4.0
243 US-Tw2  Twitchell Corn                                        CC-BY-4.0
244 US-Tw3  Twitchell Alfalfa                                     CC-BY-4.0
245 US-Tw4  Twitchell East End Wetland                            CC-BY-4.0
246 US-Tw5  East Pond Wetland                                     NA
247 US-Twt  Twitchell Island                                      CC-BY-4.0
248 US-UMB  Univ. of Mich. Biological Station                     CC-BY-4.0
249 US-UMd  UMBS Disturbance                                      CC-BY-4.0
250 US-Uaf  University of Alaska, Fairbanks                       NA
251 US-Var  Vaira Ranch- Ione                                     CC-BY-4.0
252 US-WCr  Willow Creek                                          CC-BY-4.0
253 US-WPT  Winous Point North Marsh                              CC-BY-4.0
254 US-Whs  Walnut Gulch Lucky Hills Shrub                        CC-BY-4.0
255 US-Wi0  Young red pine (YRP)                                  CC-BY-4.0
256 US-Wi1  Intermediate hardwood (IHW)                           CC-BY-4.0
257 US-Wi2  Intermediate red pine (IRP)                           CC-BY-4.0
258 US-Wi3  Mature hardwood (MHW)                                 CC-BY-4.0
259 US-Wi4  Mature red pine (MRP)                                 CC-BY-4.0
260 US-Wi5  Mixed young jack pine (MYJP)                          CC-BY-4.0
261 US-Wi6  Pine barrens #1 (PB1)                                 CC-BY-4.0
262 US-Wi7  Red pine clearcut (RPCC)                              CC-BY-4.0
263 US-Wi8  Young hardwood clearcut (YHW)                         CC-BY-4.0
264 US-Wi9  Young Jack pine (YJP)                                 CC-BY-4.0
265 US-Wkg  Walnut Gulch Kendall Grasslands                       CC-BY-4.0
266 ZA-Kru  Skukuza                                               Tier 2
267 ZM-Mon  Mongu                                                 CC-BY-4.0
    FLUXNET-CH4 LOCATION_LAT LOCATION_LONG LOCATION_ELEV IGBP MAT   MAP
1   NA          -33.4648     -66.4598        NA          MF      NA  400.00
2   NA          -28.2395     -56.1886        NA          ENF     NA      NA
3   CC-BY-4.0    47.1167      11.3175       970          GRA   6.50  852.00
4   NA          -22.2830     133.2490        NA          SAV     NA      NA
5   NA          -13.0769     131.1178        NA          WSA     NA      NA
6   NA          -34.0021     140.5891        NA          SAV     NA      NA
7   NA          -33.6152     150.7236        NA          EBF     NA      NA
8   NA          -14.0633     131.3181        NA          GRA  27.25  983.78
9   NA          -14.1593     131.3881        NA          SAV  27.22  975.82
10  NA          -15.2588     132.3706        NA          SAV     NA      NA
11  NA          -23.8587     148.4746        NA          GRA     NA      NA
12  NA          -12.5452     131.3072        NA          WET  27.02 1323.69
13  NA          -30.1913     120.6541        NA          SAV     NA      NA
14  NA          -31.3764     115.7138        NA          WSA     NA      NA
15  NA          -12.4943     131.1523        NA          WSA  27.01 1449.35
16  NA          -34.4704     140.6551        NA          DBF     NA      NA
17  NA          -14.5636     132.4776        NA          WSA     NA      NA
18  NA          -36.6499     145.5759        NA          GRA     NA      NA
19  NA          -17.1175     145.6301        NA          EBF     NA      NA
20  NA          -17.1507     133.3502        NA          GRA     NA      NA
21  NA          -22.2870     133.6400        NA          GRA     NA      NA
22  NA          -35.6566     148.1517      1200          EBF  10.72 1159.01
23  NA          -37.4259     145.1878        NA          EBF  12.76 1105.59
24  NA          -36.6732     145.0294        NA          EBF     NA      NA
25  NA          -37.4222     144.0944       705          EBF     NA      NA
26  NA          -34.9893     146.2907        NA          GRA     NA      NA
27  NA           51.3076       4.5198        16          MF    9.80  750.00
28  NA           50.5516       4.7462       167          CRO  10.00  800.00
29  NA           50.3049       5.9981       493          MF    7.80 1062.00
30  CC-BY-4.0   -16.4980     -56.4120       120          WSA  24.90 1486.00
⋮   ⋮           ⋮            ⋮             ⋮             ⋮    ⋮     ⋮
238 CC-BY-4.0    39.0882      -75.4372        6.7        WET  13.50 1121
239 NA           41.3966     -106.8024     2069.0        OSH   5.10   NA
240 NA           46.2420      -89.3477      540.0        MF    3.81  826
241 NA           38.4309     -120.9660      177.0        WSA  15.80  559
242 CC-BY-4.0    38.1074     -121.6469       -5.0        WET  15.50  421
243 NA           38.0969     -121.6365       -5.0        CRO  15.50  421
244 CC-BY-4.0    38.1152     -121.6469       -4.0        CRO  15.60  421
245 CC-BY-4.0    38.1027     -121.6413       -5.0        WET  15.60  421
246 CC-BY-4.0    38.1072     -121.6426       -5.0        WET  15.50  421
247 CC-BY-4.0    38.1087     -121.6531       -7.0        CRO  15.60  421
248 NA           45.5598      -84.7138      234.0        DBF   5.83  803
249 NA           45.5625      -84.6975      239.0        DBF   5.83  803
250 CC-BY-4.0    64.8663     -147.8555      155.0        ENF  -2.90  263
251 NA           38.4133     -120.9508      129.0        GRA  15.80  559
252 NA           45.8059      -90.0799      520.0        DBF   4.02  787
253 CC-BY-4.0    41.4646      -82.9962      175.0        WET  10.10  849
254 NA           31.7438     -110.0522     1370.0        OSH  17.60  320
255 NA           46.6188      -91.0814      349.0        ENF     NA   NA
256 NA           46.7305      -91.2329      352.0        DBF     NA   NA
257 NA           46.6869      -91.1528      395.0        ENF     NA   NA
258 NA           46.6347      -91.0987      411.0        DBF     NA   NA
259 NA           46.7393      -91.1663      352.0        ENF     NA   NA
260 NA           46.6531      -91.0858      353.0        ENF     NA   NA
261 NA           46.6249      -91.2982      371.0        OSH     NA   NA
262 NA           46.6491      -91.0693      335.0        OSH     NA   NA
263 NA           46.7223      -91.2524      348.0        DBF     NA   NA
264 NA           46.7385      -91.0746      350.0        ENF     NA   NA
265 NA           31.7365     -109.9419     1531.0        GRA  15.64  407
266 NA          -25.0197       31.4969      359.0        SAV  21.90  547
267 NA          -15.4391       23.2525     1053.0        DBF  25.00  945

In [7]:
site_metadata <- fread("combined_site_metadata.csv")

In [10]:
View(site_metadata)

    SITE_ID
1   AT-Neu
2   AU-Tum
3   AU-Wom
4   BE-Bra
5   BE-Dor
6   BE-Lcr
7   BE-Lon
8   BE-Maa
9   BE-Vie
10  BR-Npw
11  BR-Sa1
12  BR-Sa3
13  BW-Gum
14  BW-Nxr
15  CA-Gro
16  CA-Man
17  CA-NS1
18  CA-NS2
19  CA-NS3
20  CA-NS4
21  CA-NS5
22  CA-NS6
23  CA-NS7
24  CA-Oas
25  CA-Obs
26  CA-Qfo
27  CA-SCB
28  CA-SCC
29  CA-SF1
30  CA-SF2
⋮   ⋮
475 ES-Cnd
476 ES-LM1
477 ES-LM2
478 ES-Pdu
479 FI-Qvd
480 FR-EM2
481 FR-Lam
482 IE-CaC
483 IE-CaN
484 IE-Cra
485 IE-Gwr
486 IL-Yat
487 IT-BsB
488 IT-Bsn
489 IT-MtM
490 IT-MtP
491 IT-TrF
492 JP-MBF
493 JP-Mse
494 JP-Ozm
495 JP-SMF
496 JP-SwL
497 MY-MLM
498 MY-PSO
499 NZ-Kop
500 PE-QFR
501 RU-Fy2
502 RU-Fy3
503 RU-Sam
504 SE-Lnn
    SITE_NAME
1   Neustift
2   Tumbarumba
3   Wombat
4   Brasschaat
5
6
7   Lonzee
8
9   Vielsalm
10  Northern Pantanal Wetland
11  Santarem-Km67-Primary Forest
12  Santarem-Km83-Logged Forest
13  Guma
14  Nxaraga
15  Ontario - Groundhog River, Boreal Mixedwood Forest
16  Manitoba - Northern Old Black Spruce (former BOREAS Northern Study Area)
17  UCI-1850 burn site
18  UCI-1930 burn site
19  UCI-1964 burn site
20  UCI-1964 burn site wet
21  UCI-1981 burn site
22  UCI-1989 burn site
23  UCI-1998 burn site
24  Saskatchewan - Western Boreal, Mature Aspen
25  Saskatchewan - Western Boreal, Mature Black Spruce
26  Quebec - Eastern Boreal, Mature Black Spruce
27  Scotty Creek Bog
28  Scotty Creek Landscape
29  Saskatchewan - Western Boreal, forest burned in 1977
30  Saskatchewan - Western Boreal, forest burned in 1989
⋮   ⋮
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492 Moshiri Birch Forest Site
493 Mase rice paddy field
494
495 Seto Mixed Forest Site
496 Suwa Lake
497 Maludam National Park
498 Pasoh Forest Reserve (PSO)
499 Kopuatai
500
501 Fyodorovskoye dry spruce
502
503 Samoylov
504
    LOCATION_LAT LOCATION_LONG LOCATION_ELEV IGBP
1    47.11670      11.317500    970.00       GRA
2   -35.65660     148.151700   1200.00       EBF
3   -37.42220     144.094400    705.00       EBF
4    51.30761       4.519840     16.00       ENF
5    50.31188       4.968113    253.00       GRA
6    51.11218       3.850430      6.25       DBF
7    50.55162       4.746234    157.00       CRO
8    50.97987       5.631851     85.00       CSH
9    50.30496       5.998099    508.00       MF
10  -16.49800     -56.412000    120.00       WSA
11   -2.85670     -54.958900     88.00       EBF
12   -3.01800     -54.971400    100.00       EBF
13  -18.96470      22.371100    950.00       WET
14  -19.54810      23.179200    950.00       GRA
15   48.21670     -82.155600    340.00       MF
16   55.87960     -98.480800    259.00       ENF
17   55.87920     -98.483900    260.00       ENF
18   55.90580     -98.524700    260.00       ENF
19   55.91170     -98.382200    260.00       ENF
20   55.91440     -98.380600    260.00       ENF
21   55.86310     -98.485000    260.00       ENF
22   55.91670     -98.964400    244.00       OSH
23   56.63580     -99.948300    297.00       OSH
24   53.62890    -106.197800    530.00       DBF
25   53.98720    -105.117800    628.94       ENF
26   49.69250     -74.342100    382.00       ENF
27   61.30890    -121.298400    280.00       WET
28   61.30790    -121.299200    285.00       ENF
29   54.48500    -105.817600    536.00       ENF
30   54.25390    -105.877500    520.00       ENF
⋮   ⋮            ⋮             ⋮             ⋮
475  37.91500     -3.227659     366          EBF
476  39.94269     -5.778683     263          SAV
477  39.93459     -5.775881     270          SAV
478  37.01698     -3.609228     724          WET
479  60.29524     22.391607       0          CRO
480  49.87211      3.020650      84          CRO
481  43.49648      1.237850     182          CRO
482  52.85879     -6.918136      58          CRO
483  52.85879     -6.918136      58          CRO
484  53.32298     -7.641769      57          WET
485  52.63650     -7.011306      47          CRO
486  31.34504     35.051989     652          ENF
487  45.11835      7.161980     661          DBF
488  45.11931      7.160490     623          GRA
489  46.68702     10.579757    1476          GRA
490  46.68429     10.585237    1520          GRA
491  45.82376      7.560890    2084          DNF
492  44.38690    142.318600     571          DBF
493  36.05390    140.026900      12          CRO
494  34.56347    135.533480      24          URB
495  35.26170    137.078800     189          MF
496  36.04660    138.108400     760          WAT
497   1.45360    111.149500      27          EBF
498   2.97300    102.306200     132          EBF
499 -37.38790    175.553900       8          EBF
500  -3.83440    -73.319000     101          WET
501  56.44760     32.901900     275          ENF
502  56.44350     33.047800     271          ENF
503  72.37380    126.495800       0          GRA
504  58.34063     13.101768      71          CRO

In [4]:
# let's match the site names from metadata file and also flux data
# List files in renamed folder
files <- list.files(
  path = "merged_sites_subset_renamed",
  pattern = "\\.csv$",
  full.names = FALSE
)

In [5]:

# Extract SITE_ID from file names
site_ids_from_files <- files |>
  str_remove("\\.csv$") |>       # remove .csv
  str_remove("_merged$")         # remove _merged

In [8]:
matching_sites <- site_ids_from_files[site_ids_from_files %in% site_metadata$SITE_ID]

num_matching <- length(matching_sites)
num_matching

[1] 469

In [9]:
missing_sites <- setdiff(site_ids_from_files, site_metadata$SITE_ID)
missing_sites

 [1] "AR-Bal" "AR-CCa" "AR-TF2" "AU-Adr" "CA-DSM" "CA-EM2" "CA-Mer" "CA-Mtk"
 [9] "CA-SMC" "CL-ACF" "CL-SDP" "CR-Fsc" "DK-RCW" "US-A37" "US-A39" "US-CAK"
[17] "US-Cms" "US-CRK" "US-DFK" "US-DS1" "US-DS2" "US-EA5" "US-EA6" "US-Elm"
[25] "US-Esm" "US-EvM" "US-HB4" "US-Hsm" "US-HVs" "US-KPL" "US-LA3" "US-MN1"
[33] "US-MN2" "US-MN3" "US-MtB" "US-PAS" "US-PFe" "US-PFg" "US-PFh" "US-PFj"
[41] "US-PFr" "US-Sag" "US-SHC" "US-Slt" "US-UTD" "US-UTE" "US-UTJ" "US-UTP"
[49] "US-UTV" "US-xNW" "US-xRN" "US-xWR"