In [16]:
library(data.table)

In [17]:
data <- fread("derived_tables/modelready_06Mar26_no_CRO_GRA_SNO_BSV.csv")

In [18]:
str(data)

Classes ‘data.table’ and 'data.frame':	1689 obs. of  338 variables:
 $ SITE_ID               : chr  "AR-SLu" "AR-SLu" "AR-SLu" "AR-Vir" ...
 $ year                  : int  2009 2010 2011 2010 2011 2012 2017 2018 2019 2020 ...
 $ uWUE                  : num  7.68 16.24 10.69 4.07 3.75 ...
 $ ETmax                 : num  0.235 0.106 0.133 0.324 0.264 ...
 $ precipAvail           : chr  "yes" "yes" "yes" "yes" ...
 $ Gavail                : chr  "yes" "yes" "yes" "yes" ...
 $ GSmax                 : num  0.008698 0.002667 0.003875 0.000775 0.000712 ...
 $ CO2avail              : chr  "yes" "yes" "yes" "yes" ...
 $ G1                    : num  0.336 -0.55 -0.309 -0.852 -0.71 ...
 $ EF                    : num  0.313 0.149 0.253 0.827 0.773 ...
 $ EFampl                : num  0.192 0.17 0.255 0.286 0.314 ...
 $ GPPsat                : num  25.3 28.2 27.8 42.5 45.3 ...
 $ NEPmax                : num  33.5 29.5 29.2 32.7 31.4 ...
 $ Rb                    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ Rbmax                 : num  NA NA NA NA NA NA NA NA NA NA ...
 $ aCUE                  : num  NA NA NA NA NA NA NA NA NA NA ...
 $ TZ                    : int  -3 -3 -3 -3 -3 -3 8 8 8 8 ...
 $ nyears                : int  3 3 3 4 4 4 6 6 6 6 ...
 $ LOCATION_LAT          : num  -33.5 -33.5 -33.5 -28.2 -28.2 ...
 $ LOCATION_LONG         : num  -66.5 -66.5 -66.5 -56.2 -56.2 ...
 $ LOCATION_ELEV         : num  505 505 505 105 105 105 390 390 390 390 ...
 $ IGBP                  : chr  "MF" "MF" "MF" "ENF" ...
 $ P_mean_m01            : num  0.0354 0.0188 0.0371 0.0939 0.0816 ...
 $ P_mean_m02            : num  0.0276 0.0414 0.0911 0.0999 0.1269 ...
 $ P_mean_m03            : num  0.05522 0.00773 0.0191 0.14392 0.08302 ...
 $ P_mean_m04            : num  0.00405 0.00208 0.01269 0.10253 0.1059 ...
 $ P_mean_m05            : num  0.00459 0.03858 0.00403 0.06893 0.05312 ...
 $ P_mean_m06            : num  0.000185 0.000625 0.004258 0.095546 0.101163 ...
 $ P_mean_m07            : num  2.53e-03 6.72e-05 1.65e-03 1.53e-01 1.26e-01 ...
 $ P_mean_m08            : num  0.000894 0.003091 0.000648 0.014754 0.080012 ...
 $ P_mean_m09            : num  0.01542 0.02674 0.00238 0.12226 0.03946 ...
 $ P_mean_m10            : num  0.00587 0.05565 0.03212 0.07728 0.14415 ...
 $ P_mean_m11            : num  0.0306 0.0169 0.0315 0.064 0.072 ...
 $ P_mean_m12            : num  0.0608 0.0302 0.0265 0.1047 0.0197 ...
 $ P_q10_m01             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m02             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m03             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m04             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m05             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m06             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m07             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m08             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m09             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m10             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m11             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q10_m12             : num  0 0 0 0 0 0 0 0 0 0 ...
 $ P_q90_m01             : num  0 0 0 0.349 0.308 0.116 0 0 0 0 ...
 $ P_q90_m02             : num  0 0 0 0.355 0.444 0.186 0.08 0 0 0 ...
 $ P_q90_m03             : num  0 0 0 0.134 0.329 0.007 0.01 0 0 0 ...
 $ P_q90_m04             : num  0 0 0 0.371 0.304 ...
 $ P_q90_m05             : num  0 0 0 0.132 0.154 0.015 0.01 0 0 0 ...
 $ P_q90_m06             : num  0 0 0 0.307 0.476 ...
 $ P_q90_m07             : num  0 0 0 0.611 0.336 0.21 0.09 0 0 0 ...
 $ P_q90_m08             : num  0 0 0 0.01 0.17 0.09 0.09 0 0 0 ...
 $ P_q90_m09             : num  0 0 0 0.477 0.037 ...
 $ P_q90_m10             : num  0 0 0 0.047 0.269 0.498 0 0 0 0 ...
 $ P_q90_m11             : num  0 0 0.0015 0.0551 0.1093 ...
 $ P_q90_m12             : num  0.0013 0 0 0.363 0.024 ...
 $ SW_mean_m01           : num  277 366 342 297 360 ...
 $ SW_mean_m02           : num  277 299 270 297 336 ...
 $ SW_mean_m03           : num  277 269 257 296 270 ...
 $ SW_mean_m04           : num  277 210 225 297 223 ...
 $ SW_mean_m05           : num  277 145 213 297 188 ...
 $ SW_mean_m06           : num  277 127 212 297 187 ...
 $ SW_mean_m07           : num  277 157 212 297 115 ...
 $ SW_mean_m08           : num  277 176 212 296 119 ...
 $ SW_mean_m09           : num  277 216 212 304 167 ...
 $ SW_mean_m10           : num  304 279 212 328 219 ...
 $ SW_mean_m11           : num  331 333 212 321 275 ...
 $ SW_mean_m12           : num  343 361 212 300 317 ...
 $ SW_q10_m01            : num  0 0 0 0 0 ...
 $ SW_q10_m02            : num  0 0 0 0 0 ...
 $ SW_q10_m03            : num  0 0 0 0 0 ...
 $ SW_q10_m04            : num  0 0 0 0 0 ...
 $ SW_q10_m05            : num  0 0 0 0 0 ...
 $ SW_q10_m06            : num  0 0 0 0 0 ...
 $ SW_q10_m07            : num  0 0 0 0 0 ...
 $ SW_q10_m08            : num  0 0 0 0 0 ...
 $ SW_q10_m09            : num  0 0 0 0 2.08 ...
 $ SW_q10_m10            : num  0 0 0 0 2.08 ...
 $ SW_q10_m11            : num  0 0 0 0 1.56 0 2 0 0 0 ...
 $ SW_q10_m12            : num  0 0 0 0 0 0 0 0 8 0 ...
 $ SW_q90_m01            : num  932 990 966 928 964 ...
 $ SW_q90_m02            : num  932 871 858 928 972 ...
 $ SW_q90_m03            : num  932 814 805 928 951 ...
 $ SW_q90_m04            : num  932 677 747 928 849 ...
 $ SW_q90_m05            : num  932 540 747 928 630 ...
 $ SW_q90_m06            : num  932 498 747 928 630 ...
 $ SW_q90_m07            : num  932 557 747 928 455 ...
 $ SW_q90_m08            : num  932 633 747 928 455 ...
 $ SW_q90_m09            : num  932 741 747 928 609 ...
 $ SW_q90_m10            : num  932 866 747 928 813 ...
 $ SW_q90_m11            : num  932 970 747 960 945 ...
 $ SW_q90_m12            : num  912 1026 747 996 967 ...
 $ TA_mean_m01           : num  -9999 28.5 27.2 27.3 28.3 ...
 $ TA_mean_m02           : num  -9999 26.7 24.7 27.9 27.1 ...
 $ TA_mean_m03           : num  -9999 25.7 22.3 25.9 24.3 ...
 $ TA_mean_m04           : num  -9999 18.5 -6673.7 21.1 21.4 ...
 $ TA_mean_m05           : num  -9999 13.5 -9999 17 18.3 ...
  [list output truncated]
 - attr(*, ".internal.selfref")=<externalptr>

In [19]:
names(data)

  [1] "SITE_ID"                "year"                   "uWUE"
  [4] "ETmax"                  "precipAvail"            "Gavail"
  [7] "GSmax"                  "CO2avail"               "G1"
 [10] "EF"                     "EFampl"                 "GPPsat"
 [13] "NEPmax"                 "Rb"                     "Rbmax"
 [16] "aCUE"                   "TZ"                     "nyears"
 [19] "LOCATION_LAT"           "LOCATION_LONG"          "LOCATION_ELEV"
 [22] "IGBP"                   "P_mean_m01"             "P_mean_m02"
 [25] "P_mean_m03"             "P_mean_m04"             "P_mean_m05"
 [28] "P_mean_m06"             "P_mean_m07"             "P_mean_m08"
 [31] "P_mean_m09"             "P_mean_m10"             "P_mean_m11"
 [34] "P_mean_m12"             "P_q10_m01"              "P_q10_m02"
 [37] "P_q10_m03"              "P_q10_m04"              "P_q10_m05"
 [40] "P_q10_m06"              "P_q10_m07"              "P_q10_m08"
 [43] "P_q10_m09"              "P_q10_m10"              "P_q10_m11"
 [46] "P_q10_m12"              "P_q90_m01"              "P_q90_m02"
 [49] "P_q90_m03"              "P_q90_m04"              "P_q90_m05"
 [52] "P_q90_m06"              "P_q90_m07"              "P_q90_m08"
 [55] "P_q90_m09"              "P_q90_m10"              "P_q90_m11"
 [58] "P_q90_m12"              "SW_mean_m01"            "SW_mean_m02"
 [61] "SW_mean_m03"            "SW_mean_m04"            "SW_mean_m05"
 [64] "SW_mean_m06"            "SW_mean_m07"            "SW_mean_m08"
 [67] "SW_mean_m09"            "SW_mean_m10"            "SW_mean_m11"
 [70] "SW_mean_m12"            "SW_q10_m01"             "SW_q10_m02"
 [73] "SW_q10_m03"             "SW_q10_m04"             "SW_q10_m05"
 [76] "SW_q10_m06"             "SW_q10_m07"             "SW_q10_m08"
 [79] "SW_q10_m09"             "SW_q10_m10"             "SW_q10_m11"
 [82] "SW_q10_m12"             "SW_q90_m01"             "SW_q90_m02"
 [85] "SW_q90_m03"             "SW_q90_m04"             "SW_q90_m05"
 [88] "SW_q90_m06"             "SW_q90_m07"             "SW_q90_m08"
 [91] "SW_q90_m09"             "SW_q90_m10"             "SW_q90_m11"
 [94] "SW_q90_m12"             "TA_mean_m01"            "TA_mean_m02"
 [97] "TA_mean_m03"            "TA_mean_m04"            "TA_mean_m05"
[100] "TA_mean_m06"            "TA_mean_m07"            "TA_mean_m08"
[103] "TA_mean_m09"            "TA_mean_m10"            "TA_mean_m11"
[106] "TA_mean_m12"            "TA_q10_m01"             "TA_q10_m02"
[109] "TA_q10_m03"             "TA_q10_m04"             "TA_q10_m05"
[112] "TA_q10_m06"             "TA_q10_m07"             "TA_q10_m08"
[115] "TA_q10_m09"             "TA_q10_m10"             "TA_q10_m11"
[118] "TA_q10_m12"             "TA_q90_m01"             "TA_q90_m02"
[121] "TA_q90_m03"             "TA_q90_m04"             "TA_q90_m05"
[124] "TA_q90_m06"             "TA_q90_m07"             "TA_q90_m08"
[127] "TA_q90_m09"             "TA_q90_m10"             "TA_q90_m11"
[130] "TA_q90_m12"             "VPD_mean_m01"           "VPD_mean_m02"
[133] "VPD_mean_m03"           "VPD_mean_m04"           "VPD_mean_m05"
[136] "VPD_mean_m06"           "VPD_mean_m07"           "VPD_mean_m08"
[139] "VPD_mean_m09"           "VPD_mean_m10"           "VPD_mean_m11"
[142] "VPD_mean_m12"           "VPD_q10_m01"            "VPD_q10_m02"
[145] "VPD_q10_m03"            "VPD_q10_m04"            "VPD_q10_m05"
[148] "VPD_q10_m06"            "VPD_q10_m07"            "VPD_q10_m08"
[151] "VPD_q10_m09"            "VPD_q10_m10"            "VPD_q10_m11"
[154] "VPD_q10_m12"            "VPD_q90_m01"            "VPD_q90_m02"
[157] "VPD_q90_m03"            "VPD_q90_m04"            "VPD_q90_m05"
[160] "VPD_q90_m06"            "VPD_q90_m07"            "VPD_q90_m08"
[163] "VPD_q90_m09"            "VPD_q90_m10"            "VPD_q90_m11"
[166] "VPD_q90_m12"            "P_mean_m01.y"           "P_mean_m02.y"
[169] "P_mean_m03.y"           "P_mean_m04.y"           "P_mean_m05.y"
[172] "P_mean_m06.y"           "P_mean_m07.y"           "P_mean_m08.y"
[175] "P_mean_m09.y"           "P_mean_m10.y"           "P_mean_m11.y"
[178] "P_mean_m12.y"           "P_q10_m01.y"            "P_q10_m02.y"
[181] "P_q10_m03.y"            "P_q10_m04.y"            "P_q10_m05.y"
[184] "P_q10_m06.y"            "P_q10_m07.y"            "P_q10_m08.y"
[187] "P_q10_m09.y"            "P_q10_m10.y"            "P_q10_m11.y"
[190] "P_q10_m12.y"            "P_q90_m01.y"            "P_q90_m02.y"
[193] "P_q90_m03.y"            "P_q90_m04.y"            "P_q90_m05.y"
[196] "P_q90_m06.y"            "P_q90_m07.y"            "P_q90_m08.y"
[199] "P_q90_m09.y"            "P_q90_m10.y"            "P_q90_m11.y"
[202] "P_q90_m12.y"            "SW_mean_m01.y"          "SW_mean_m02.y"
[205] "SW_mean_m03.y"          "SW_mean_m04.y"          "SW_mean_m05.y"
[208] "SW_mean_m06.y"          "SW_mean_m07.y"          "SW_mean_m08.y"
[211] "SW_mean_m09.y"          "SW_mean_m10.y"          "SW_mean_m11.y"
[214] "SW_mean_m12.y"          "SW_q10_m01.y"           "SW_q10_m02.y"
[217] "SW_q10_m03.y"           "SW_q10_m04.y"           "SW_q10_m05.y"
[220] "SW_q10_m06.y"           "SW_q10_m07.y"           "SW_q10_m08.y"
[223] "SW_q10_m09.y"           "SW_q10_m10.y"           "SW_q10_m11.y"
[226] "SW_q10_m12.y"           "SW_q90_m01.y"           "SW_q90_m02.y"
[229] "SW_q90_m03.y"           "SW_q90_m04.y"           "SW_q90_m05.y"
[232] "SW_q90_m06.y"           "SW_q90_m07.y"           "SW_q90_m08.y"
[235] "SW_q90_m09.y"           "SW_q90_m10.y"           "SW_q90_m11.y"
[238] "SW_q90_m12.y"           "TA_mean_m01.y"          "TA_mean_m02.y"
[241] "TA_mean_m03.y"          "TA_mean_m04.y"          "TA_mean_m05.y"
[244] "TA_mean_m06.y"          "TA_mean_m07.y"          "TA_mean_m08.y"
[247] "TA_mean_m09.y"          "TA_mean_m10.y"          "TA_mean_m11.y"
[250] "TA_mean_m12.y"          "TA_q10_m01.y"           "TA_q10_m02.y"
[253] "TA_q10_m03.y"           "TA_q10_m04.y"           "TA_q10_m05.y"
[256] "TA_q10_m06.y"           "TA_q10_m07.y"           "TA_q10_m08.y"
[259] "TA_q10_m09.y"           "TA_q10_m10.y"           "TA_q10_m11.y"
[262] "TA_q10_m12.y"           "TA_q90_m01.y"           "TA_q90_m02.y"
[265] "TA_q90_m03.y"           "TA_q90_m04.y"           "TA_q90_m05.y"
[268] "TA_q90_m06.y"           "TA_q90_m07.y"           "TA_q90_m08.y"
[271] "TA_q90_m09.y"           "TA_q90_m10.y"           "TA_q90_m11.y"
[274] "TA_q90_m12.y"           "VPD_mean_m01.y"         "VPD_mean_m02.y"
[277] "VPD_mean_m03.y"         "VPD_mean_m04.y"         "VPD_mean_m05.y"
[280] "VPD_mean_m06.y"         "VPD_mean_m07.y"         "VPD_mean_m08.y"
[283] "VPD_mean_m09.y"         "VPD_mean_m10.y"         "VPD_mean_m11.y"
[286] "VPD_mean_m12.y"         "VPD_q10_m01.y"          "VPD_q10_m02.y"
[289] "VPD_q10_m03.y"          "VPD_q10_m04.y"          "VPD_q10_m05.y"
[292] "VPD_q10_m06.y"          "VPD_q10_m07.y"          "VPD_q10_m08.y"
[295] "VPD_q10_m09.y"          "VPD_q10_m10.y"          "VPD_q10_m11.y"
[298] "VPD_q10_m12.y"          "VPD_q90_m01.y"          "VPD_q90_m02.y"
[301] "VPD_q90_m03.y"          "VPD_q90_m04.y"          "VPD_q90_m05.y"
[304] "VPD_q90_m06.y"          "VPD_q90_m07.y"          "VPD_q90_m08.y"
[307] "VPD_q90_m09.y"          "VPD_q90_m10.y"          "VPD_q90_m11.y"
[310] "VPD_q90_m12.y"          "gsmax_mean"             "P12_mean"
[313] "P50_mean"               "P88_mean"               "rdmax_mean"
[316] "WUE_mean"               "Leaf C"                 "Leaf N (mass)"
[319] "Leaf width"             "Leaf C/N ratio"         "Leaf P"
[322] "Stem conduit density"   "Stem conduit diameter"  "Leaf area (3112)"
[325] "Leaf area"              "Leaf area (3114)"       "SLA"
[328] "SSD"                    "Leaf thickness"         "Leaf N (area)"
[331] "Leaf dry mass"          "Rooting depth"          "Leaf delta 15N"
[334] "forest_mean_pct_500m.x" "deadwood_mean_pct_500m" "loss_area_frac_500m"
[337] "loss_mean_pp_500m"      "loss_sum_pp_500m"

In [15]:
View(data)

     SITE_ID year uWUE       ETmax      precipAvail Gavail GSmax
1    AR-SLu  2009  7.6758122 0.23525256 yes         yes    0.0086978262
2    AR-SLu  2010 16.2402893 0.10641401 yes         yes    0.0026672316
3    AR-SLu  2011 10.6928793 0.13295070 yes         yes    0.0038752408
4    AR-Vir  2010  4.0743924 0.32438591 yes         yes    0.0007750829
5    AR-Vir  2011  3.7541200 0.26378451 yes         yes    0.0007116720
6    AR-Vir  2012  4.3087226 0.26984531 yes         yes    0.0006417871
7    AU-Boy  2017  0.7899208 0.11600305 yes         yes    0.0130617409
8    AU-Boy  2018  0.7711226 0.10568721 yes         yes    0.0170890362
9    AU-Boy  2019  1.0517841 0.09239969 yes         yes    0.0156257134
10   AU-Boy  2020  1.4732505 0.08067205 yes         yes    0.0135019907
11   AU-Boy  2021  1.2432836 0.11402598 yes         yes    0.0197534833
12   AU-Boy  2022  1.3295602 0.11021342 yes         yes    0.0214978328
13   AU-GWW  2013  0.7697647 0.08086202 yes         yes    0.0107684157
14   AU-GWW  2014  0.8931195 0.09695582 yes         yes    0.0096556043
15   AU-GWW  2015  0.6998805 0.07906207 yes         yes    0.0075112864
16   AU-GWW  2016  0.5329357 0.07056603 yes         yes    0.0085116536
17   AU-GWW  2017  0.5955004 0.07065226 yes         yes    0.0066820491
18   AU-GWW  2018  0.7405456 0.08910414 yes         yes    0.0086981071
19   AU-GWW  2019  0.9367222 0.06960913 yes         yes    0.0071550108
20   AU-GWW  2020  1.6981964 0.07193393 yes         yes    0.0068668343
21   AU-GWW  2021  1.7050668 0.06961746 yes         yes    0.0065835042
22   AU-GWW  2022  2.3811295 0.05308200 yes         yes    0.0034405848
23   AU-Gin  2011  2.7403292 0.17309879 yes         yes    0.0046949386
24   AU-Gin  2012  3.1773704 0.13795972 yes         yes    0.0043759459
25   AU-Gin  2013  3.0131258 0.12434229 yes         yes    0.0041765185
26   AU-Gin  2014  3.4892150 0.12581627 yes         yes    0.0041778902
27   AU-Rob  2014  2.8264971 0.26119488 yes         yes    0.0108603364
28   AU-Wac  2005  2.7336379 0.22435294 yes         yes    0.0219977721
29   AU-Wac  2006  2.7177068 0.21829448 yes         yes    0.0153155879
30   AU-Wac  2007  2.7939568 0.21133969 yes         yes    0.0160427270
⋮    ⋮       ⋮    ⋮          ⋮          ⋮           ⋮      ⋮
1660 US-xTL  2019 1.463101   0.1100805  yes         yes    1.056467e-02
1661 US-xTL  2021 1.442952   0.1019592  yes         yes    6.527409e-03
1662 US-xTL  2022 1.101925   0.1086952  yes         yes    6.529965e-03
1663 US-xTL  2023 1.523674   0.1095428  yes         yes    6.138782e-03
1664 US-xTL  2024 1.193763   0.1175551  yes         yes    6.893137e-03
1665 US-xTR  2019 3.282404   0.3042587  yes         yes    1.318486e-02
1666 US-xTR  2020 3.176859   0.3062168  yes         yes    1.474091e-02
1667 US-xTR  2021 3.604890   0.2546764  yes         yes    1.309808e-02
1668 US-xTR  2022 3.701912   0.2403326  yes         yes    1.118832e-02
1669 US-xTR  2023 3.880713   0.2291475  yes         yes    9.722346e-03
1670 US-xTR  2024 3.698216   0.2402754  yes         yes    1.135013e-02
1671 US-xUK  2020 3.883338   0.3277433  yes         yes    1.196106e-02
1672 US-xUK  2021 3.328095   0.3149820  yes         yes    1.080341e-02
1673 US-xUK  2022 3.366104   0.2944972  yes         yes    8.957806e-03
1674 US-xUK  2023 3.716226   0.2817669  yes         yes    8.737278e-03
1675 US-xUK  2024 3.629790   0.2964053  yes         yes    9.640685e-03
1676 US-xUN  2019 3.169772   0.2525124  yes         yes    1.376494e-02
1677 US-xUN  2020 3.091840   0.2524902  yes         yes    1.305483e-02
1678 US-xUN  2021 3.412614   0.2156285  yes         yes    9.177107e-03
1679 US-xUN  2022 3.158563   0.2413102  yes         yes    1.122145e-02
1680 US-xUN  2023 4.047444   0.2270125  yes         yes    1.048224e-02
1681 US-xUN  2024 3.691778   0.2110452  yes         yes    1.006742e-02
1682 ZA-Kru  2000 3.565617   0.1948224  yes         yes    9.059350e-03
1683 ZA-Kru  2001 4.241298   0.2029507  yes         yes    4.019003e-03
1684 ZA-Kru  2003 3.389522   0.1753666  yes         yes    4.040004e-03
1685 ZA-Kru  2004 3.999096   0.4011044  yes         yes    2.429775e-07
1686 ZA-Kru  2005 2.722959   0.4486521  yes         yes    6.231033e-07
1687 ZM-Mon  2007 3.700569   0.2140455  yes         yes    6.424542e-03
1688 ZM-Mon  2008 3.094234   0.2244055  yes         yes    8.911256e-03
1689 ZM-Mon  2009 2.833322   0.2439872  yes         yes    1.051414e-02
     CO2avail G1         EF         ⋯ Leaf thickness Leaf N (area)
1    yes       0.3358437 0.31273212 ⋯ 0.2711317      1.922857
2    yes      -0.5497535 0.14924966 ⋯ 0.2711317      1.922857
3    yes      -0.3088108 0.25332098 ⋯ 0.2711317      1.922857
4    yes      -0.8520437 0.82715766 ⋯ 0.2042549      1.432450
5    yes      -0.7099170 0.77276878 ⋯ 0.2042549      1.432450
6    yes      -1.0401099 0.67272836 ⋯ 0.2042549      1.432450
7    yes       2.4988547 0.23464725 ⋯ 0.3032645      1.723632
8    yes       2.5197002 0.21973094 ⋯ 0.3032645      1.723632
9    yes       1.7396987 0.18559788 ⋯ 0.3032645      1.723632
10   yes       1.5718601 0.16713881 ⋯ 0.3032645      1.723632
11   yes       2.1182052 0.24657534 ⋯ 0.3032645      1.723632
12   yes       1.7474465 0.24390244 ⋯ 0.3032645      1.723632
13   yes       2.9790288 0.16571429 ⋯ 0.3076166      3.042108
14   yes       2.2540639 0.17808219 ⋯ 0.3076166      3.042108
15   yes       3.0666866 0.13427562 ⋯ 0.3076166      3.042108
16   yes       3.3611937 0.13684211 ⋯ 0.3076166      3.042108
17   yes       2.8720108 0.12887828 ⋯ 0.3076166      3.042108
18   yes       2.7726786 0.17073171 ⋯ 0.3076166      3.042108
19   yes       1.8700513 0.12903226 ⋯ 0.3076166      3.042108
20   yes       1.0643522 0.11981567 ⋯ 0.3076166      3.042108
21   yes       0.9906611 0.12403611 ⋯ 0.3076166      3.042108
22   yes       0.4763078 0.08645882 ⋯ 0.3076166      3.042108
23   yes       2.6354922 0.35655380 ⋯ 0.3126940      2.083258
24   yes       2.1973158 0.30769231 ⋯ 0.3126940      2.083258
25   yes       2.5452199 0.30534351 ⋯ 0.3126940      2.083258
26   yes       2.0013301 0.26802963 ⋯ 0.3126940      2.083258
27   yes       1.8691018 0.49664086 ⋯ 0.2358074      1.492418
28   yes       3.2010233 0.43706294 ⋯ 0.2543037      1.515476
29   yes       2.5835292 0.46112293 ⋯ 0.2543037      1.515476
30   yes       3.0202737 0.45971593 ⋯ 0.2543037      1.515476
⋮    ⋮        ⋮          ⋮          ⋱ ⋮              ⋮
1660 yes       3.8676560 0.4782403  ⋯ 0.2442214      1.864256
1661 yes       3.7817130 0.4623090  ⋯ 0.2442214      1.864256
1662 yes       6.2025418 0.5260447  ⋯ 0.2442214      1.864256
1663 yes       5.2819752 0.5538138  ⋯ 0.2442214      1.864256
1664 yes       6.7093825 0.4866161  ⋯ 0.2442214      1.864256
1665 yes       2.4000234 0.6619096  ⋯ 0.1962035      1.115112
1666 yes       2.7780887 0.6974950  ⋯ 0.1962035      1.115112
1667 yes       2.0877296 0.6546542  ⋯ 0.1962035      1.115112
1668 yes       2.0137818 0.5824445  ⋯ 0.1962035      1.115112
1669 yes       1.7169085 0.5776330  ⋯ 0.1962035      1.115112
1670 yes       1.8016329 0.5774201  ⋯ 0.1962035      1.115112
1671 yes       1.4290114 0.7963936  ⋯ 0.2007007      1.155030
1672 yes       2.0986010 0.7824520  ⋯ 0.2007007      1.155030
1673 yes       1.9722885 0.6833704  ⋯ 0.2007007      1.155030
1674 yes       1.6078253 0.6716639  ⋯ 0.2007007      1.155030
1675 yes       1.8217500 0.7107241  ⋯ 0.2007007      1.155030
1676 yes       2.8814232 0.6641444  ⋯ 0.1771270      1.125593
1677 yes       2.8165195 0.6828900  ⋯ 0.1771270      1.125593
1678 yes       2.0835489 0.6254987  ⋯ 0.1771270      1.125593
1679 yes       2.5596081 0.6420018  ⋯ 0.1771270      1.125593
1680 yes       1.8048624 0.6594843  ⋯ 0.1771270      1.125593
1681 yes       2.0175539 0.6500806  ⋯ 0.1771270      1.125593
1682 yes       1.8748086 0.5001348  ⋯ 0.2107830      1.595859
1683 yes      -0.2344621 0.4267669  ⋯ 0.2107830      1.595859
1684 yes       1.2822339 0.3561213  ⋯ 0.2107830      1.595859
1685 yes      -1.0638285 0.5653098  ⋯ 0.2107830      1.595859
1686 yes      -1.3153986 0.5530980  ⋯ 0.2107830      1.595859
1687 yes       1.4849267 0.4807903  ⋯ 0.2158604      1.507456
1688 yes       2.0898202 0.5115970  ⋯ 0.2158604      1.507456
1689 yes       2.0708050 0.5796605  ⋯ 0.2158604      1.507456
     Leaf dry mass Rooting depth Leaf delta 15N forest_mean_pct_500m.x
1     53.15581     0.6918347      1.80658666           NA
2     53.15581     0.6918347      1.80658666           NA
3     53.15581     0.6918347      1.80658666           NA
4    107.23314     1.0653660      0.71522217           NA
5    107.23314     1.0653660      0.71522217           NA
6    107.23314     1.0653660      0.71522217           NA
7     42.43594     0.6918347     -0.09699274    24.975004
8     42.43594     0.6918347     -0.09699274    11.883699
9     42.43594     0.6918347     -0.09699274     9.653346
10    42.43594     0.6918347     -0.09699274     8.829368
11    42.43594     0.6918347     -0.09699274    10.812703
12    42.43594     0.6918347     -0.09699274    22.552462
13    47.14722     1.3483443      0.89185920           NA
14    47.14722     1.3483443      0.89185920           NA
15    47.14722     1.3483443      0.89185920           NA
16    47.14722     1.3483443      0.89185920    12.998802
17    47.14722     1.3483443      0.89185920    17.219877
18    47.14722     1.3483443      0.89185920    19.548473
19    47.14722     1.3483443      0.89185920    19.536446
20    47.14722     1.3483443      0.89185920    21.112858
21    47.14722     1.3483443      0.89185920    20.088013
22    47.14722     1.3483443      0.89185920    18.330441
23    43.46013     0.7937069     -0.67158879           NA
24    43.46013     0.7937069     -0.67158879           NA
25    43.46013     0.7937069     -0.67158879           NA
26    43.46013     0.7937069     -0.67158879           NA
27   228.90713     1.5520886      0.93470419           NA
28    44.82572     0.5673243     -0.67080023           NA
29    44.82572     0.5673243     -0.67080023           NA
30    44.82572     0.5673243     -0.67080023           NA
⋮    ⋮             ⋮             ⋮              ⋮
1660  23.65909     0.2617078     -0.9110476     8.980692e-04
1661  23.65909     0.2617078     -0.9110476     6.486055e-04
1662  23.65909     0.2617078     -0.9110476     0.000000e+00
1663  23.65909     0.2617078     -0.9110476     1.147533e-03
1664  23.65909     0.2617078     -0.9110476     1.396997e-03
1665  55.13592     0.3748991     -1.0535138     3.146785e+00
1666  55.13592     0.3748991     -1.0535138     6.705184e+00
1667  55.13592     0.3748991     -1.0535138     1.496782e-03
1668  55.13592     0.3748991     -1.0535138     0.000000e+00
1669  55.13592     0.3748991     -1.0535138     9.692313e+00
1670  55.13592     0.3748991     -1.0535138     9.583197e+00
1671  62.03214     0.5220478      0.1461460     6.746630e+01
1672  62.03214     0.5220478      0.1461460     5.863334e+01
1673  62.03214     0.5220478      0.1461460     4.628159e+01
1674  62.03214     0.5220478      0.1461460     5.404565e+01
1675  62.03214     0.5220478      0.1461460     6.662356e+01
1676  67.49450     0.4428138     -1.1954543     9.076366e+01
1677  67.49450     0.4428138     -1.1954543     8.954018e+01
1678  67.49450     0.4428138     -1.1954543     9.326299e+01
1679  67.49450     0.4428138     -1.1954543     9.215591e+01
1680  67.49450     0.4428138     -1.1954543     9.376486e+01
1681  67.49450     0.4428138     -1.1954543     9.165804e+01
1682 108.73529     0.7823878      1.7419249               NA
1683 108.73529     0.7823878      1.7419249               NA
1684 108.73529     0.7823878      1.7419249               NA
1685 108.73529     0.7823878      1.7419249               NA
1686 108.73529     0.7823878      1.7419249               NA
1687 121.77667     0.8050260      1.5434711               NA
1688 121.77667     0.8050260      1.5434711               NA
1689 121.77667     0.8050260      1.5434711               NA
     deadwood_mean_pct_500m loss_area_frac_500m loss_mean_pp_500m
1          NA                         NA                 NA
2          NA                         NA                 NA
3          NA                         NA                 NA
4          NA                         NA                 NA
5          NA                         NA                 NA
6          NA                         NA                 NA
7    3.441002               0.0000000000        0.000000000
8    2.638078               0.2361323155        6.270069351
9    1.253954               0.0020356234        0.043256997
10   2.406826               0.0304071247        0.739909195
11   3.156114               0.0001272265        0.002544529
12   4.341017               0.0000000000        0.000000000
13         NA                         NA                 NA
14         NA                         NA                 NA
15         NA                         NA                 NA
16   2.413810                         NA                 NA
17   5.691813               0.0096692112        0.225515142
18   5.071397               0.0001272265        0.002943671
19   5.356184               0.0000000000        0.000000000
20   4.416055               0.0000000000        0.000000000
21   3.158260               0.0000000000        0.000000000
22   3.628249               0.0000000000        0.000000000
23         NA                         NA                 NA
24         NA                         NA                 NA
25         NA                         NA                 NA
26         NA                         NA                 NA
27         NA                         NA                 NA
28         NA                         NA                 NA
29         NA                         NA                 NA
30         NA                         NA                 NA
⋮    ⋮                      ⋮                   ⋮
1660 0.0031931351           0.0000000000        0.000000000
1661 0.0006486055           0.0001272265        0.003442598
1662 0.0000000000           0.0000000000        0.000000000
1663 0.0015466748           0.0000000000        0.000000000
1664 0.0000000000           0.0000000000        0.000000000
1665 0.0054882006           0.0000000000        0.000000000
1666 0.0075338022           0.0000000000        0.000000000
1667 0.0032430275           0.0991094148        2.750735918
1668 0.0000000000           0.0000000000        0.000000000
1669 0.0019957093           0.0000000000        0.000000000
1670 0.0046400242           0.0008905852        0.021054732
1671 2.5032682419           0.0021628499        0.048695305
1672 4.0242481232           0.1160305344        2.861198423
1673 5.7430024147           0.2452926209        6.617821683
1674 7.4506807327           0.0010178117        0.022002694
1675 2.8136508465           0.0185750636        0.578456319
1676 3.8430378437           0.0001272265        0.002793993
1677 2.5922267437           0.0015267176        0.035074590
1678 1.7797734737           0.0000000000        0.000000000
1679 2.1213889122           0.0033078880        0.076236092
1680 2.1203413010           0.0000000000        0.000000000
1681 1.1770693064           0.0086513995        0.239784463
1682           NA                     NA                 NA
1683           NA                     NA                 NA
1684           NA                     NA                 NA
1685           NA                     NA                 NA
1686           NA                     NA                 NA
1687           NA                     NA                 NA
1688           NA                     NA                 NA
1689           NA                     NA                 NA
     loss_sum_pp_500m
1             NA
2             NA
3             NA
4             NA
5             NA
6             NA
7        0.00000
8    49282.74510
9      340.00000
10    5815.68627
11      20.00000
12       0.00000
13            NA
14            NA
15            NA
16            NA
17    1772.54902
18      23.13725
19       0.00000
20       0.00000
21       0.00000
22       0.00000
23            NA
24            NA
25            NA
26            NA
27            NA
28            NA
29            NA
30            NA
⋮    ⋮
1660     0.00000
1661    27.05882
1662     0.00000
1663     0.00000
1664     0.00000
1665     0.00000
1666     0.00000
1667 21620.78431
1668     0.00000
1669     0.00000
1670   165.49020
1671   382.74510
1672 22489.01961
1673 52016.07843
1674   172.94118
1675  4546.66667
1676    21.96078
1677   275.68627
1678     0.00000
1679   599.21569
1680     0.00000
1681  1884.70588
1682          NA
1683          NA
1684          NA
1685          NA
1686          NA
1687          NA
1688          NA
1689          NA

In [9]:
unique(data$IGBP)

 [1] "MF"  "ENF" "EBF" "SAV" "WSA" "DNF" "WET" "DBF" "OSH" "CSH" "CVM"

In [12]:
### Let's remove NAs across all columns and see how many rows will be left
data <- data[complete.cases(data)]
nrow(data)

[1] 14

In [4]:
library(data.table)

data <- as.data.table(data)  # your dataset

# keep .x, drop .y (or vice versa)
data[, c("P_mm.y","Tair_mean_C.y","SWin_mean_Wm2.y","VPD_GS_hPa.y") := NULL]

# clean names
setnames(data,
         old = c("P_mm.x","Tair_mean_C.x","SWin_mean_Wm2.x","VPD_GS_hPa.x"),
         new = c("P_mm","Tair_mean_C","SWin_mean_Wm2","VPD_GS_hPa"))

In [6]:
# set physically impossible values to NA
data[Tair_mean_C < -50 | Tair_mean_C > 60, Tair_mean_C := NA]
data[VPD_GS_hPa < 0 | VPD_GS_hPa > 500, VPD_GS_hPa := NA]
data[P_mm < 0 | P_mm > 10000, P_mm := NA]
data[SWin_mean_Wm2 < 0 | SWin_mean_Wm2 > 500, SWin_mean_Wm2 := NA]

In [7]:
fwrite(data, "derived_tables/EFP_climate_deadwood_trait_500m_yearly.csv")

In [22]:
#### datacleaning:

library(data.table)

df <- data
# make sure it's a data.table
setDT(df)

In [23]:
# =========================================================
# 1) REPLACE COMMON MISSING VALUE CODES WITH NA
# =========================================================

missing_codes <- c(-9999, -9999.0, -6999, -6999.0, -7999, -7999.0)

num_cols <- names(df)[sapply(df, is.numeric)]

for (col in num_cols) {
  df[get(col) %in% missing_codes, (col) := NA_real_]
}

In [24]:
# =========================================================
# 2) IDENTIFY COLUMN GROUPS
# =========================================================

ta_cols  <- grep("^TA_", names(df), value = TRUE)
vpd_cols <- grep("^VPD_", names(df), value = TRUE)
sw_cols  <- grep("^SW_", names(df), value = TRUE)
p_cols   <- grep("^P_", names(df), value = TRUE)

# deadwood / forest / loss columns if present
deadwood_cols <- grep("deadwood", names(df), value = TRUE, ignore.case = TRUE)
forest_cols   <- grep("forest", names(df), value = TRUE, ignore.case = TRUE)
loss_cols     <- grep("loss", names(df), value = TRUE, ignore.case = TRUE)

In [25]:
# =========================================================
# 3) RANGE-BASED CLEANING
# =========================================================

# ---- Temperature (deg C) ----
# monthly means / quantiles outside these bounds are treated as impossible
for (col in ta_cols) {
  df[get(col) < -80 | get(col) > 60, (col) := NA_real_]
}

# ---- VPD ----
# should not be negative; upper bound can be adjusted
for (col in vpd_cols) {
  df[get(col) < 0 | get(col) > 20, (col) := NA_real_]
}

# ---- Shortwave radiation ----
# should not be negative
for (col in sw_cols) {
  df[get(col) < 0 | get(col) > 1500, (col) := NA_real_]
}

# ---- Precipitation ----
# should not be negative
for (col in p_cols) {
  df[get(col) < 0, (col) := NA_real_]
}

# ---- Fraction / percent variables ----
# adapt depending on units
# If values are proportions: 0-1
# If values are percentages: 0-100
#
# From your names, these might already be percentages, so check first.
fraction_like_cols <- unique(c(deadwood_cols, forest_cols, loss_cols))

for (col in fraction_like_cols) {
  # first only remove impossible negatives
  df[get(col) < 0, (col) := NA_real_]
}

In [30]:
# =========================================================
# 4) OPTIONAL: CHECK FOR REMAINING EXTREME VALUES
# =========================================================

check_extremes <- function(cols, data) {
  if (length(cols) == 0) return(NULL)
  data.table(
    variable = cols,
    min = sapply(cols, function(x) suppressWarnings(min(data[[x]], na.rm = TRUE))),
    max = sapply(cols, function(x) suppressWarnings(max(data[[x]], na.rm = TRUE))),
    n_na = sapply(cols, function(x) sum(is.na(data[[x]])))
  )
}

ta_check  <- check_extremes(ta_cols, df)
vpd_check <- check_extremes(vpd_cols, df)
sw_check  <- check_extremes(sw_cols, df)
p_check   <- check_extremes(p_cols, df)

cat("TA extremes:\n")
print(head(ta_check[order(min)], 20))

cat("\nVPD extremes:\n")
print(head(vpd_check[order(min)], 20))

cat("\nSW extremes:\n")
print(head(sw_check[order(min)], 20))

cat("\nP extremes:\n")
print(head(p_check[order(min)], 20))

TA extremes:
       variable       min      max  n_na
         <char>     <num>    <num> <int>
 1:  TA_q10_m01 -46.20000 24.00000   132
 2:  TA_q10_m12 -45.58700 25.06000    85
 3:  TA_q10_m02 -44.67800 24.05100   125
 4: TA_mean_m01 -40.58535 28.49345   132
 5:  TA_q10_m03 -38.82300 24.20000   115
 6:  TA_q10_m11 -37.93510 25.06200    79
 7: TA_mean_m02 -37.29621 29.45458   125
 8:  TA_q90_m01 -35.80000 37.71100   126
 9: TA_mean_m12 -35.19182 29.70856    86
10: TA_mean_m03 -32.35181 29.90025   116
11:  TA_q10_m10 -31.57290 29.09860    68
12:  TA_q10_m04 -30.37600 25.78800   108
13:  TA_q90_m12 -29.77300 37.66800    80
14:  TA_q90_m02 -29.62500 37.41800   117
15:  TA_q10_m05 -29.07600 27.33900    89
16: TA_mean_m11 -27.53190 29.53994    83
17: TA_mean_m04 -24.72574 32.84656   109
18:  TA_q90_m03 -24.09400 39.77480   105
19:  TA_q90_m11 -19.39500 37.90800    66
20:  TA_q90_m04 -19.09570 39.82500    90
       variable       min      max  n_na
         <char>     <num>    <num> <int>

VPD extremes:
        variable         min      max  n_na
          <char>       <num>    <num> <int>
 1:  VPD_q10_m01 0.000000000 15.24120   188
 2:  VPD_q10_m02 0.000000000 17.34670   181
 3:  VPD_q10_m03 0.000000000 19.63970   171
 4:  VPD_q10_m04 0.000000000 17.63810   168
 5:  VPD_q10_m05 0.000000000 17.36450   149
 6:  VPD_q10_m06 0.000000000 19.98680   134
 7:  VPD_q10_m07 0.000000000 19.43670   109
 8:  VPD_q10_m08 0.000000000 19.50130   103
 9:  VPD_q10_m09 0.000000000 16.59990    99
10:  VPD_q10_m10 0.000000000 12.68070   124
11:  VPD_q10_m11 0.000000000 15.27500   135
12:  VPD_q10_m12 0.000000000 15.18090   141
13:  VPD_q90_m01 0.000000000 19.98230   215
14:  VPD_q90_m02 0.000000000 19.59500   228
15:  VPD_q90_m11 0.000000000 19.90720   202
16:  VPD_q90_m12 0.000000000 19.80520   172
17: VPD_mean_m11 0.004320833 19.92400   146
18: VPD_mean_m02 0.007392113 18.60908   191
19:  VPD_q90_m10 0.030300000 19.94250   305
20: VPD_mean_m12 0.034489919 18.31062   152
        variable         min      max  n_na
          <char>       <num>    <num> <int>

SW extremes:
       variable   min       max  n_na
         <char> <num>     <num> <int>
 1: SW_mean_m11     0  362.9576   110
 2: SW_mean_m12     0  376.0544   111
 3:  SW_q10_m01     0    3.6090   160
 4:  SW_q10_m02     0   27.0590   154
 5:  SW_q10_m03     0   27.0590   142
 6:  SW_q10_m04     0   27.0590   131
 7:  SW_q10_m05     0   43.7839   114
 8:  SW_q10_m06     0   44.0467    96
 9:  SW_q10_m07     0   29.3146    76
10:  SW_q10_m08     0    7.0000    74
11:  SW_q10_m09     0    7.0000    69
12:  SW_q10_m10     0    6.1950    96
13:  SW_q10_m11     0    8.0000   107
14:  SW_q10_m12     0   12.9296   111
15:  SW_q90_m01     0 1062.6000   152
16:  SW_q90_m02     0 1000.7000   147
17:  SW_q90_m03     0  950.5600   131
18:  SW_q90_m09     0  932.4520    59
19:  SW_q90_m11     0 1039.0000    94
20:  SW_q90_m12     0 1067.0000   103
       variable   min       max  n_na
         <char> <num>     <num> <int>

P extremes:
      variable   min       max  n_na
        <char> <num>     <num> <int>
 1: P_mean_m01     0 0.9757379     2
 2: P_mean_m02     0 0.6900937     2
 3: P_mean_m03     0 1.1776210     2
 4: P_mean_m04     0 0.8550694     2
 5: P_mean_m05     0 0.7518320     4
 6: P_mean_m06     0 0.7200000     4
 7: P_mean_m07     0 0.5477392     6
 8: P_mean_m08     0 0.6484892     9
 9: P_mean_m09     0 0.9235625    10
10: P_mean_m10     0 8.3664026    10
11: P_mean_m11     0 6.4788722    10
12: P_mean_m12     0 0.8681331    10
13:  P_q10_m01     0 0.0070000     2
14:  P_q10_m02     0 0.2140000     2
15:  P_q10_m03     0 0.0020000     2
16:  P_q10_m04     0 0.0160000     2
17:  P_q10_m05     0 0.0070000     4
18:  P_q10_m06     0 0.0110000     4
19:  P_q10_m07     0 0.0040000     6
20:  P_q10_m08     0 0.0070000     9
      variable   min       max  n_na
        <char> <num>     <num> <int>

In [31]:
df[, .(
  forest_min = min(forest_mean_pct_500m.x, na.rm = TRUE),
  forest_max = max(forest_mean_pct_500m.x, na.rm = TRUE),
  deadwood_min = min(deadwood_mean_pct_500m, na.rm = TRUE),
  deadwood_max = max(deadwood_mean_pct_500m, na.rm = TRUE),
  loss_frac_min = min(loss_area_frac_500m, na.rm = TRUE),
  loss_frac_max = max(loss_area_frac_500m, na.rm = TRUE),
  loss_pp_min = min(loss_mean_pp_500m, na.rm = TRUE),
  loss_pp_max = max(loss_mean_pp_500m, na.rm = TRUE)
)]

  forest_min forest_max deadwood_min deadwood_max loss_frac_min loss_frac_max
1 0          94.18391   0            51.05019     0             0.6648855
  loss_pp_min loss_pp_max
1 0           38.35683

In [28]:
dup_y_cols <- grep("\\.y$", names(df), value = TRUE)

compare_dup_cols <- data.table(
  col_y = dup_y_cols,
  col_base = sub("\\.y$", "", dup_y_cols)
)

compare_dup_cols[, identical_values := mapply(
  function(ycol, bcol) {
    if (!bcol %in% names(df)) return(FALSE)
    all((is.na(df[[ycol]]) & is.na(df[[bcol]])) | (df[[ycol]] == df[[bcol]]), na.rm = FALSE)
  },
  col_y, col_base
)]

print(compare_dup_cols)

             col_y    col_base identical_values
            <char>      <char>           <lgcl>
  1:  P_mean_m01.y  P_mean_m01             TRUE
  2:  P_mean_m02.y  P_mean_m02             TRUE
  3:  P_mean_m03.y  P_mean_m03             TRUE
  4:  P_mean_m04.y  P_mean_m04             TRUE
  5:  P_mean_m05.y  P_mean_m05             TRUE
 ---
140: VPD_q90_m08.y VPD_q90_m08             TRUE
141: VPD_q90_m09.y VPD_q90_m09             TRUE
142: VPD_q90_m10.y VPD_q90_m10             TRUE
143: VPD_q90_m11.y VPD_q90_m11             TRUE
144: VPD_q90_m12.y VPD_q90_m12             TRUE

In [29]:
cols_to_drop <- compare_dup_cols[identical_values == TRUE, col_y]
df[, (cols_to_drop) := NULL]

In [32]:
fwrite(df, "derived_tables/modelready_06Mar26_no_CRO_GRA_SNO_BSV.csv")